#!/usr/bin/env bash
# Monoceros devcontainer feature: github-cli.
#
# Installs the official GitHub CLI (`gh`) from cli.github.com's apt
# repository. When the `token` option is set, the value is exposed
# as GH_TOKEN via /etc/profile.d so every login shell sees an
# authenticated `gh`. Without a token, `gh` is installed but
# unauthenticated; the builder can run `gh auth login` once
# interactively and the resulting `~/.config/gh/` state is
# persisted via Monoceros' bind-mount.

set -euo pipefail

APITOKEN="${APITOKEN:-}"

echo "[github-cli] installing gh from cli.github.com apt repo"

# Per https://cli.github.com/manual/installation (Debian/Ubuntu path).
type -p curl >/dev/null || {
  apt-get update
  apt-get install -y curl
}

curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
  | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg

mkdir -p -m 755 /etc/apt/sources.list.d
ARCH="$(dpkg --print-architecture)"
echo "deb [arch=${ARCH} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
  > /etc/apt/sources.list.d/github-cli.list

apt-get update
apt-get install -y --no-install-recommends gh

gh --version >/dev/null 2>&1 || {
  echo "[github-cli] ERROR: install completed but \`gh\` is not on PATH" >&2
  exit 1
}

# ─── Refresh hook (ADR 0054) ──────────────────────────────────────
# The feature has no version option: `gh` is always the current one, so there
# is no builder pin to respect here and the hook is unconditional.
REFRESH_DIR=/usr/local/share/monoceros/refresh.d
mkdir -p "${REFRESH_DIR}"
cat >"${REFRESH_DIR}/github-cli.sh" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by the Monoceros github-cli feature.
#
# Keeps `gh` current across applies (ADR 0054). `gh` lands in a cached apt
# layer, and every apply recreates the container from that layer, so the
# builder would otherwise keep the version that was current when the layer was
# first built. `gh` only prints "a new release is available" and never updates
# itself, so nothing else would ever move it — and a `gh` a few months old
# starts meeting removed API endpoints and changed auth flows.
#
# apt does the version comparison itself: `--only-upgrade` is a no-op when the
# installed version is the newest one the repo offers.
#
# The update is scoped to the cli.github.com list on purpose. A plain
# `apt-get update` refreshes every configured repo, which is tens of megabytes
# and several seconds for an answer we do not need — this one asks the single
# repo that can move `gh`. `List-Cleanup=0` keeps that partial update from
# evicting the other repos' cached lists.
#
# Deliberately no `set -e`: best-effort by contract, an apt or network problem
# must never fail an apply.
set -u

GH_LIST=/etc/apt/sources.list.d/github-cli.list

note() {
  [ -n "${MONOCEROS_REFRESH_LOG:-}" ] || return 0
  printf '%s\n' "$1" >>"${MONOCEROS_REFRESH_LOG}" 2>/dev/null || true
}

version_of() {
  gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1
}

installed="$(version_of)"

if [ ! -f "${GH_LIST}" ]; then
  note "gh: apt source missing, keeping ${installed:-the version from the image}"
  exit 0
fi

if ! sudo apt-get update \
  -o Dir::Etc::sourcelist="${GH_LIST}" \
  -o Dir::Etc::sourceparts=/dev/null \
  -o APT::Get::List-Cleanup=0 >/dev/null 2>&1; then
  note "gh: could not reach the apt repo, keeping ${installed:-the version from the image}"
  exit 0
fi

if ! sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --only-upgrade gh \
  >/dev/null 2>&1; then
  note "gh: update failed, keeping ${installed:-the version from the image}"
  exit 0
fi

now="$(version_of)"
if [ "${now}" = "${installed}" ]; then
  note "gh ${now:-unknown} (already current)"
else
  note "gh ${now:-unknown} (updated from ${installed:-unknown})"
fi
HOOK
chmod 0755 "${REFRESH_DIR}/github-cli.sh"

if [ -n "${APITOKEN}" ]; then
  cat >/etc/profile.d/github-cli.sh <<EOF
# Auto-generated by the Monoceros github-cli feature. Exports
# GH_TOKEN so the GitHub CLI authenticates non-interactively.
export GH_TOKEN='${APITOKEN}'
EOF
  chmod 0644 /etc/profile.d/github-cli.sh
  echo "[github-cli] apiToken wired via /etc/profile.d/ → \`gh\` authenticated in login shells"
else
  echo "[github-cli] no apiToken set — run \`gh auth login\` once in the container; auth state persists under ~/.config/gh"
fi

echo "[github-cli] done"
