#!/usr/bin/env bash
# Monoceros devcontainer feature: atlassian.
#
# Installs Atlassian CLIs that share a single Atlassian account:
#   - Rovo Dev (acli, default on) — the `acli rovodev` AI agent
#   - Teamwork Graph (twg, default off)
#
# Each tool is toggled independently via the `rovodev` / `twg`
# options. Credentials (instance / email / apiToken) are shared
# across both tools when set; per-tool post-create hooks under
# /usr/local/share/monoceros/post-create.d/ perform the
# non-interactive login on first container start.

set -euo pipefail

ROVODEV="${ROVODEV:-true}"
TWG="${TWG:-false}"
INSTANCE="${INSTANCE:-}"
EMAIL="${EMAIL:-}"
APITOKEN="${APITOKEN:-}"

if [ "${ROVODEV}" != "true" ] && [ "${TWG}" != "true" ]; then
  echo "[atlassian] both rovodev and twg disabled — nothing to install" >&2
  exit 0
fi

ARCH="$(dpkg --print-architecture)"
case "${ARCH}" in
  amd64 | arm64) ;;
  *)
    echo "[atlassian] unsupported architecture: ${ARCH}" >&2
    exit 1
    ;;
esac

POST_CREATE_DIR=/usr/local/share/monoceros/post-create.d
mkdir -p "${POST_CREATE_DIR}"

# ─── Rovo Dev (acli) ──────────────────────────────────────────────
if [ "${ROVODEV}" = "true" ]; then
  ACLI_URL="https://acli.atlassian.com/linux/latest/acli_linux_${ARCH}/acli"
  echo "[atlassian/rovodev] downloading acli for ${ARCH} from ${ACLI_URL}"
  TMP="$(mktemp)"
  curl -fsSL -o "${TMP}" "${ACLI_URL}"
  install -o root -g root -m 0755 "${TMP}" /usr/local/bin/acli
  rm -f "${TMP}"
  acli --version >/dev/null 2>&1 || {
    echo "[atlassian/rovodev] ERROR: install completed but \`acli\` is not on PATH" >&2
    exit 1
  }

  HOOK="${POST_CREATE_DIR}/atlassian-rovodev.sh"
  if [ -n "${EMAIL}" ] && [ -n "${APITOKEN}" ]; then
    cat >"${HOOK}" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Monoceros atlassian feature (rovodev).
# Runs once per container start; skips when already authenticated.
set -euo pipefail
CFG="\${HOME}/.config/acli/rovodev_config.yaml"
if [ -f "\${CFG}" ] && grep -q '^[[:space:]]*auth_type:[[:space:]]*api_token' "\${CFG}"; then
  echo "[atlassian/rovodev] already authenticated, skipping login"
  exit 0
fi
echo "[atlassian/rovodev] performing non-interactive Rovo Dev login for ${EMAIL}"
echo '${APITOKEN}' | acli rovodev auth login --email '${EMAIL}' --token
echo "[atlassian/rovodev] auth login done — on first \\\`acli rovodev run\\\` you'll be asked for your Atlassian site once; the answer persists."
EOF
    chmod 0755 "${HOOK}"
    echo "[atlassian/rovodev] post-create login hook installed"
  else
    rm -f "${HOOK}"
    echo "[atlassian/rovodev] no email/apiToken set — login is manual (\`acli rovodev auth login\` once in the container)"
  fi
fi

# ─── Teamwork Graph (twg) ─────────────────────────────────────────
if [ "${TWG}" = "true" ]; then
  echo "[atlassian/twg] installing via official install script"
  TMP="$(mktemp)"
  curl -fsSL -o "${TMP}" https://teamwork-graph.atlassian.com/cli/install
  bash "${TMP}"
  rm -f "${TMP}"

  # The install script may drop the binary in a user-mode location.
  # Promote it to /usr/local/bin so every user/shell in the container
  # finds it. If it's already on PATH (because the script wrote into
  # a system dir), the for-loop just no-ops.
  if ! command -v twg >/dev/null 2>&1; then
    for cand in \
      "${HOME:-/root}/.local/bin/twg" \
      /root/.local/bin/twg \
      /usr/local/share/twg/twg \
      /opt/twg/twg; do
      if [ -x "${cand}" ]; then
        install -o root -g root -m 0755 "${cand}" /usr/local/bin/twg
        break
      fi
    done
  fi
  twg --version >/dev/null 2>&1 || {
    echo "[atlassian/twg] ERROR: install completed but \`twg\` is not on PATH" >&2
    exit 1
  }

  HOOK="${POST_CREATE_DIR}/atlassian-twg.sh"
  if [ -n "${INSTANCE}" ] && [ -n "${EMAIL}" ] && [ -n "${APITOKEN}" ]; then
    cat >"${HOOK}" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Monoceros atlassian feature (twg).
# Runs once per container start; skips when already authenticated.
set -euo pipefail
CFG="\${HOME}/.config/twg/auth.conf"
if [ -f "\${CFG}" ] && [ -s "\${CFG}" ]; then
  echo "[atlassian/twg] already authenticated, skipping login"
  exit 0
fi
echo "[atlassian/twg] configuring twg non-interactively for ${EMAIL} @ ${INSTANCE}"
mkdir -p "\${HOME}/.config/twg"
TWG_USER='${EMAIL}' TWG_SITE='${INSTANCE}' TWG_TOKEN='${APITOKEN}' twg login --force
EOF
    chmod 0755 "${HOOK}"
    echo "[atlassian/twg] post-create login hook installed"
  else
    rm -f "${HOOK}"
    echo "[atlassian/twg] missing instance/email/apiToken — login is manual (\`twg login\` once in the container)"
  fi
fi

echo "[atlassian] done"
