#!/usr/bin/env bash
# Monoceros devcontainer feature: atlassian.
#
# Installs the Atlassian Command Line Interface (`acli`) from the
# official Atlassian download endpoint. The same binary contains the
# Rovo Dev subcommand (`acli rovodev`); future Atlassian-tool additions
# (twg, etc.) will become separate features.
#
# ACLI's config and credential store lives at /home/node/.config/acli.
# Monoceros bind-mounts that path from <container-dir>/home/.config/acli
# so the login survives `monoceros apply` rebuilds.
#
# When the feature's three Atlassian options (instance, email, apiToken)
# are all set, we drop a post-create hook that does a non-interactive
# login via `acli rovodev auth login --token`. The post-create hook is
# the right layer for the login because the bind-mount isn't available
# during install (mounts come up at container start, not feature-install
# time).

set -euo pipefail

ARCH="$(dpkg --print-architecture)"
case "${ARCH}" in
  amd64 | arm64) ;;
  *)
    echo "[atlassian] unsupported architecture: ${ARCH}" >&2
    exit 1
    ;;
esac

URL="https://acli.atlassian.com/linux/latest/acli_linux_${ARCH}/acli"
echo "[atlassian] downloading acli for ${ARCH} from ${URL}"

TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

curl -fsSL -o "${TMP}" "${URL}"
install -o root -g root -m 0755 "${TMP}" /usr/local/bin/acli

acli --version >/dev/null 2>&1 || {
  echo "[atlassian] ERROR: install completed but \`acli\` is not on PATH" >&2
  exit 1
}

# Drop the post-create login hook. The hook runs as `node` from the
# scaffold's post-create.sh, *after* the bind-mount on
# /home/node/.config/acli is live, so the credentials we write actually
# persist back to the host.
#
# Idempotency: if /home/node/.config/acli/rovodev_config.yaml already
# carries an `auth_type: api_token` line we skip the login (already
# logged in from a previous run, or the builder did it interactively).
#
# Rovo Dev's `auth login` only accepts `--email` and `--token` — the
# site/instance is asked by `acli rovodev run` itself on first launch
# and persisted under ~/.config/acli/. So the feature only needs
# email + apiToken for the auto-login step.
EMAIL="${EMAIL:-}"
APITOKEN="${APITOKEN:-}"

POST_CREATE_DIR=/usr/local/share/monoceros/post-create.d
mkdir -p "${POST_CREATE_DIR}"
HOOK="${POST_CREATE_DIR}/atlassian.sh"

if [ -n "${EMAIL}" ] && [ -n "${APITOKEN}" ]; then
  cat >"${HOOK}" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Monoceros atlassian feature. Runs once per
# container start; skips the login if a token is already on file.
set -euo pipefail

CFG="\${HOME}/.config/acli/rovodev_config.yaml"
if [ -f "\${CFG}" ] && grep -q '^[[:space:]]*auth_type:[[:space:]]*api_token' "\${CFG}"; then
  echo "[atlassian] already authenticated, skipping login"
  exit 0
fi

echo "[atlassian] performing non-interactive Rovo Dev login for ${EMAIL}"
echo '${APITOKEN}' | acli rovodev auth login --email '${EMAIL}' --token
echo "[atlassian] auth login done — on first \\\`acli rovodev run\\\` you'll be asked for your Atlassian site once; the answer persists."
EOF
  chmod 0755 "${HOOK}"
  echo "[atlassian] post-create login hook installed at ${HOOK}"
else
  # No auto-login → leave a note for whoever's debugging why they're
  # still being prompted. Removing the hook means a future re-apply
  # with credentials picks it up cleanly.
  rm -f "${HOOK}"
  echo "[atlassian] no email/apiToken set — login is manual (run \`acli rovodev auth login\` once in the container)"
fi

echo "[atlassian] done — \`acli\` $(acli --version 2>&1 | head -n 1) installed"
