#!/usr/bin/env bash
# Monoceros devcontainer feature: atlassian.
#
# Installs Atlassian CLIs that share a single Atlassian account:
#   - Rovo Dev (acli, default on) — the `acli rovodev` AI agent
#   - Teamwork Graph (twg, default on)
#   - Forge (forge, default on) — the `@forge/cli` app-dev toolchain
#
# Each tool is toggled independently via the `rovodev` / `twg` / `forge`
# options. Credentials (instance / email / apiToken) are shared across
# the tools when set; rovodev and twg get per-tool post-create hooks
# under /usr/local/share/monoceros/post-create.d/ that perform the
# non-interactive login on first container start. Forge has no login
# hook: it reads FORGE_EMAIL / FORGE_API_TOKEN from the workspace
# runtime env, which the workbench injects from the shared account
# options (feature.workspaceEnv) — the keychain-free path Atlassian
# recommends for containers.

set -euo pipefail

ROVODEV="${ROVODEV:-true}"
TWG="${TWG:-true}"
FORGE="${FORGE:-true}"
INSTANCE="${INSTANCE:-}"
EMAIL="${EMAIL:-}"
APITOKEN="${APITOKEN:-}"
BITBUCKETTOKEN="${BITBUCKETTOKEN:-}"

if [ "${ROVODEV}" != "true" ] && [ "${TWG}" != "true" ] && [ "${FORGE}" != "true" ]; then
  echo "[atlassian] rovodev, twg and forge all disabled — nothing to install" >&2
  exit 0
fi

ARCH="$(dpkg --print-architecture)"
case "${ARCH}" in
  amd64 | arm64) ;;
  *)
    echo "[atlassian] unsupported architecture: ${ARCH}" >&2
    exit 1
    ;;
esac

POST_CREATE_DIR=/usr/local/share/monoceros/post-create.d
mkdir -p "${POST_CREATE_DIR}"

# ─── Rovo Dev (acli) ──────────────────────────────────────────────
if [ "${ROVODEV}" = "true" ]; then
  ACLI_URL="https://acli.atlassian.com/linux/latest/acli_linux_${ARCH}/acli"
  echo "[atlassian/rovodev] downloading acli for ${ARCH} from ${ACLI_URL}"
  TMP="$(mktemp)"
  curl -fsSL -o "${TMP}" "${ACLI_URL}"
  install -o root -g root -m 0755 "${TMP}" /usr/local/bin/acli
  rm -f "${TMP}"
  acli --version >/dev/null 2>&1 || {
    echo "[atlassian/rovodev] ERROR: install completed but \`acli\` is not on PATH" >&2
    exit 1
  }

  HOOK="${POST_CREATE_DIR}/atlassian-rovodev.sh"
  if [ -n "${EMAIL}" ] && [ -n "${APITOKEN}" ]; then
    cat >"${HOOK}" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Monoceros atlassian feature (rovodev).
# Runs every container start. Always re-runs auth login so that
# rotating the apiToken in the container yml propagates through on
# the next \`monoceros apply\` without needing to delete the
# previous credentials file by hand. acli's login is a single API
# call; the cost is negligible compared to the container build.
set -euo pipefail
echo "[atlassian/rovodev] performing non-interactive Rovo Dev login for ${EMAIL}"
echo '${APITOKEN}' | acli rovodev auth login --email '${EMAIL}' --token
echo "[atlassian/rovodev] auth login done — on first \\\`acli rovodev run\\\` you'll be asked for your Atlassian site once; the answer persists."
EOF
    chmod 0755 "${HOOK}"
    echo "[atlassian/rovodev] post-create login hook installed"
  else
    rm -f "${HOOK}"
    echo "[atlassian/rovodev] no email/apiToken set — login is manual (\`acli rovodev auth login\` once in the container)"
  fi
fi

# ─── Teamwork Graph (twg) ─────────────────────────────────────────
if [ "${TWG}" = "true" ]; then
  echo "[atlassian/twg] installing via official install script"
  TMP="$(mktemp)"
  curl -fsSL -o "${TMP}" https://teamwork-graph.atlassian.com/cli/install
  # The official install script:
  #   - Downloads the binary; we pin install dir to /usr/local/bin so
  #     both root (build time) and node (runtime) have it on PATH.
  #   - Runs a `twg consent --source direct-public-installer` step
  #     that prompts on stdin. We feed it `yes` via a heredoc; the
  #     extra blank lines are harmless padding in case a future
  #     version adds more prompts. (The recorded consent lands in
  #     /root/.config/twg/ which is not visible to the node user at
  #     runtime — we re-record it as node in the post-create hook
  #     below.)
  #   - With --skip-login / --skip-skills we keep the install
  #     non-interactive. Login + skills happen later as the node user
  #     so they persist into the bind-mounted home.
  #
  # Heredoc (not `yes ... |`) deliberately: a long-lived `yes` left
  # writing into a closed pipe after the install script exits gets
  # SIGPIPE'd, and our own `set -o pipefail` would then propagate
  # that 141 as a feature-install failure even though the install
  # actually succeeded.
  bash "${TMP}" \
    --install-dir /usr/local/bin \
    --skip-login \
    --skip-skills \
    <<'TWG_INSTALL_INPUT'
yes
yes
yes
TWG_INSTALL_INPUT
  rm -f "${TMP}"

  # The install script's mktemp + chmod +x leaves twg-bin at 0700
  # (only root can execute it). Re-chmod so the node user can run it.
  if [ -f /usr/local/bin/twg-bin ]; then
    chmod 0755 /usr/local/bin/twg-bin
  fi
  if [ -f /usr/local/bin/twg ]; then
    chmod 0755 /usr/local/bin/twg
  fi

  twg --version >/dev/null 2>&1 || {
    echo "[atlassian/twg] ERROR: install completed but \`twg\` is not on PATH" >&2
    exit 1
  }

  HOOK="${POST_CREATE_DIR}/atlassian-twg.sh"
  if [ -n "${INSTANCE}" ] && [ -n "${EMAIL}" ] && [ -n "${APITOKEN}" ]; then
    cat >"${HOOK}" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Monoceros atlassian feature (twg).
# Runs every container start. Always re-runs auth login so that
# rotating the apiToken / bitbucketToken in the container yml
# propagates through on the next \`monoceros apply\` without
# needing to delete the previous credentials file by hand. twg's
# login is a single API call; the cost is negligible compared to
# the container build.
set -euo pipefail
mkdir -p "\${HOME}/.config/twg"
echo "[atlassian/twg] configuring twg non-interactively for ${EMAIL} @ ${INSTANCE}"
# Notes on the non-interactive login dance:
#   - We don't try to re-record consent here as the node user. twg's
#     \`consent\` subcommand demands a TTY; the install-time consent
#     (recorded as root during the feature build) appears to be
#     enough for \`twg login\` itself.
#   - \`twg login --force\` reads Atlassian creds from TWG_USER /
#     TWG_SITE / TWG_TOKEN. If TWG_BBC_TOKEN is set, twg uses that
#     directly and skips the Bitbucket prompt. If empty, twg prompts
#     interactively — we feed two blank lines via heredoc so the
#     "Enter = skip" branch fires and we don't hang. Future twg
#     versions adding another optional prompt are also covered by
#     the second blank line.
TWG_USER='${EMAIL}' \\
TWG_SITE='${INSTANCE}' \\
TWG_TOKEN='${APITOKEN}' \\
TWG_BBC_TOKEN='${BITBUCKETTOKEN}' \\
  twg login --force <<'TWG_LOGIN_INPUT'


TWG_LOGIN_INPUT

# (Re-)install twg's agent skills. Canonical install lands in
# /home/node/.agents/skills/twg (persisted via the feature's
# persistentHomePaths); .agents/skills-native agents (codex, cursor,
# gemini, copilot, …) read it directly. Agents with their own skills
# dir (claude → .claude/skills, opencode → .opencode/skills) need an
# explicit --agent flag, so we detect which AI CLIs are present in this
# container and pass the matching flags. This keeps the atlassian
# feature decoupled from the container's feature list — it reacts to
# whatever is actually installed. Idempotent: re-running just refreshes
# the wrappers.
echo "[atlassian/twg] (re-)installing twg skills"
TWG_SKILL_AGENTS=()
if command -v claude >/dev/null 2>&1; then
  TWG_SKILL_AGENTS+=(--agent claude)
fi
if command -v opencode >/dev/null 2>&1; then
  TWG_SKILL_AGENTS+=(--agent opencode)
fi
twg skills install --global --yes "\${TWG_SKILL_AGENTS[@]}"
EOF
    chmod 0755 "${HOOK}"
    echo "[atlassian/twg] post-create login hook installed"
  else
    rm -f "${HOOK}"
    echo "[atlassian/twg] missing instance/email/apiToken — login is manual (\`twg login\` once in the container)"
  fi
fi

# ─── Forge (@forge/cli) ───────────────────────────────────────────
if [ "${FORGE}" = "true" ]; then
  # Forge is a Node CLI; the runtime ships Node, so a global npm install
  # is enough. No post-create login hook: `forge login` stores creds in
  # the OS keychain (libsecret on Linux), which we deliberately do not
  # carry. Instead Forge reads FORGE_EMAIL / FORGE_API_TOKEN at command
  # time; the workbench injects them into the workspace runtime env from
  # this feature's `email` / `apiToken` options (feature.workspaceEnv),
  # so the right account is in scope without a login step here.
  echo "[atlassian/forge] installing @forge/cli globally via npm"
  npm install -g @forge/cli
  forge --version >/dev/null 2>&1 || {
    echo "[atlassian/forge] ERROR: install completed but \`forge\` is not on PATH" >&2
    exit 1
  }
  if [ -z "${EMAIL}" ] || [ -z "${APITOKEN}" ]; then
    echo "[atlassian/forge] no email/apiToken set — set them in the container yml so FORGE_EMAIL/FORGE_API_TOKEN reach the shell"
  fi
fi

echo "[atlassian] done"
