#!/usr/bin/env bash
# Monoceros devcontainer feature: browser.
#
# Installs a headless Chromium and the Playwright MCP server that drives it,
# so an agent can look at the app it builds (ADR 0060).
#
# Chromium comes from Debian rather than from Playwright's own download. The
# MCP server floats to latest, and each Playwright release asks for its own
# browser revision; a revision downloaded at build time would stop matching
# the first time the server updates underneath it. The Debian package is a
# fixed path the server is pointed at instead (`--executable-path`), and it
# pulls in every shared library a browser needs, which is also what lets a
# project's own `npx playwright install` work without `--with-deps`.
#
# The MCP registration does NOT happen here. It lands in each agent's config
# at apply, from the descriptor's `mcpServer:` block (ADR 0045), because those
# configs live in bind-mounted home paths a build-time write would not reach.

set -euo pipefail

VERSION="${VERSION:-latest}"

echo "[browser] installing chromium from Debian"
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends chromium
rm -rf /var/lib/apt/lists/*

# The package registers itself as the system's web browser. In this container
# "open a browser" means the builder's own, through the host browser bridge
# (ADR 0022), and a Chromium without a display would only fail, so take the
# registration back out.
update-alternatives --remove x-www-browser /usr/bin/chromium
update-alternatives --remove gnome-www-browser /usr/bin/chromium

# Start it once, the way the MCP server will. A browser that installs and then
# cannot run (a missing library, a CPU the build does not support) should fail
# the build here, not the agent's first page load.
chromium --headless --no-sandbox --disable-gpu --dump-dom about:blank >/dev/null 2>&1 || {
  echo "[browser] ERROR: chromium is installed but does not start headless" >&2
  exit 1
}

echo "[browser] installing @playwright/mcp@${VERSION} (as node)"

# As node, not root, for the same reason as the other npm-installed features:
# the global prefix is node-owned, so the refresh hook below can update the
# package without sudo (ADR 0018).
runuser -u node -- bash -lc \
  "npm install -g --no-audit --no-fund '@playwright/mcp@${VERSION}'"

runuser -u node -- bash -lc 'playwright-mcp --version' >/dev/null 2>&1 || {
  echo "[browser] ERROR: install completed but \`playwright-mcp\` is not on PATH" >&2
  exit 1
}

# ─── Refresh hook (ADR 0054) ──────────────────────────────────────
# Only when the version is unpinned. A builder who wrote a version into the
# yml decided which one they want, and an apply does not overrule that.
if [ "${VERSION}" = "latest" ]; then
  REFRESH_DIR=/usr/local/share/monoceros/refresh.d
  mkdir -p "${REFRESH_DIR}"
  cat >"${REFRESH_DIR}/browser.sh" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by the Monoceros browser feature.
#
# Keeps `@playwright/mcp` current across applies (ADR 0054). The version
# installed at build time lives in a cached image layer, and every apply
# recreates the container from that layer.
#
# Version-checked rather than a blind install: one registry lookup, and npm
# only runs when the two versions actually differ.
#
# Deliberately no `set -e` and no `pipefail`: best-effort by contract, a
# registry outage must never fail an apply.
set -u

PKG='@playwright/mcp'

note() {
  [ -n "${MONOCEROS_REFRESH_LOG:-}" ] || return 0
  printf '%s\n' "$1" >>"${MONOCEROS_REFRESH_LOG}" 2>/dev/null || true
}

version_of() {
  playwright-mcp --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1
}

installed="$(version_of)"
latest="$(npm view "${PKG}" version 2>/dev/null | tr -d '[:space:]')"

if [ -z "${latest}" ]; then
  note "playwright-mcp: could not reach the npm registry, keeping ${installed:-the version from the image}"
  exit 0
fi

if [ "${installed}" = "${latest}" ]; then
  note "playwright-mcp ${installed} (already current)"
  exit 0
fi

if npm install -g --no-audit --no-fund "${PKG}@${latest}" >/dev/null 2>&1; then
  note "playwright-mcp ${latest} (updated from ${installed:-unknown})"
else
  note "playwright-mcp: update to ${latest} failed, keeping ${installed:-the version from the image}"
fi
HOOK
  chmod 0755 "${REFRESH_DIR}/browser.sh"
fi

echo "[browser] installed - the playwright MCP server is registered with each agent by \`monoceros apply\`"
echo "[browser] done"
