#!/usr/bin/env bash
# Monoceros devcontainer feature: opencode.
#
# Installs sst's OpenCode CLI globally via the npm registry (package
# `opencode-ai`). Model selection and the provider API key are NOT
# handled here — they are written to ~/.config/opencode/opencode.json
# at `monoceros apply` (see create/opencode-config.ts), so a change to
# the yml takes effect on the next apply instead of being frozen by the
# feature's cached image layer (ADR 0018). Auth/session state lives
# under ~/.config/opencode and ~/.local/share/opencode, both
# bind-mounted from the host so they survive apply rebuilds.

set -euo pipefail

VERSION="${VERSION:-latest}"

echo "[opencode] installing opencode-ai@${VERSION} (as node)"

# Install as the non-root `node` user, NOT root (this script runs as
# root). The base image's npm global prefix is owned by `node`, so
# installing as node leaves the package files node-owned — which is what
# lets OpenCode's runtime self-updater keep itself current between
# Monoceros `upgrade`s. Installing as root would freeze the version at
# build time with no-write-permission errors. Same rationale as the
# claude-code feature (ADR 0018).
runuser -u node -- bash -lc \
  "npm install -g --no-audit --no-fund 'opencode-ai@${VERSION}'"

runuser -u node -- bash -lc 'opencode --version' >/dev/null 2>&1 || {
  echo "[opencode] ERROR: install completed but \`opencode\` is not on PATH" >&2
  exit 1
}

# ─── Refresh hook (ADR 0054) ──────────────────────────────────────
# Only when the version is unpinned. A builder who wrote a version into the
# yml decided which one they want, and an apply does not overrule that.
if [ "${VERSION}" = "latest" ]; then
  REFRESH_DIR=/usr/local/share/monoceros/refresh.d
  mkdir -p "${REFRESH_DIR}"
  cat >"${REFRESH_DIR}/opencode.sh" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by the Monoceros opencode feature.
#
# Keeps `opencode` current across applies (ADR 0054). The version installed at
# build time lives in a cached image layer, and every apply recreates the
# container from that layer — so without this the builder falls back to
# whatever was current when the layer was first built, losing the self-update
# the previous container had applied.
#
# Version-checked rather than a blind install: one registry lookup, and npm
# only runs when the two versions actually differ.
#
# Deliberately no `set -e` and no `pipefail`: best-effort by contract, a
# registry outage must never fail an apply.
set -u

PKG='opencode-ai'

note() {
  [ -n "${MONOCEROS_REFRESH_LOG:-}" ] || return 0
  printf '%s\n' "$1" >>"${MONOCEROS_REFRESH_LOG}" 2>/dev/null || true
}

version_of() {
  opencode --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1
}

installed="$(version_of)"
latest="$(npm view "${PKG}" version 2>/dev/null | tr -d '[:space:]')"

if [ -z "${latest}" ]; then
  note "opencode: could not reach the npm registry, keeping ${installed:-the version from the image}"
  exit 0
fi

if [ "${installed}" = "${latest}" ]; then
  note "opencode ${installed} (already current)"
  exit 0
fi

if npm install -g --no-audit --no-fund "${PKG}@${latest}" >/dev/null 2>&1; then
  note "opencode ${latest} (updated from ${installed:-unknown})"
else
  note "opencode: update to ${latest} failed, keeping ${installed:-the version from the image}"
fi
HOOK
  chmod 0755 "${REFRESH_DIR}/opencode.sh"
fi

echo "[opencode] installed — model + provider key (if set in the yml) are written to ~/.config/opencode/opencode.json by \`monoceros apply\`; otherwise run \`opencode auth login\` once in the container"
echo "[opencode] done"
