import { fileURLToPath } from 'node:url';
import { describe, expect, it, vi } from 'vitest';
import type * as PathsModule from '../src/config/paths.js';

// The bundled-manifest dir, in the same `<dir>/<name>/devcontainer-feature.json`
// layout the published tarball ships. We point it at the always-present
// source `images/features/` rather than the real `bundledFeaturesDir()`
// (`packages/cli/features/`): the latter is generated by
// `pnpm manifests:sync` (prebuild) and is absent in a test-only CI job,
// which would make this test flap on build state instead of behavior.
const IMAGES_FEATURES_DIR = fileURLToPath(
  new URL('../../../images/features', import.meta.url),
);

// Simulate the production (npm-installed) CLI: no workbench checkout, so
// `workbenchCheckoutRoot()` returns null and the prod branch reads the
// feature's persistent-home entries from the bundled manifest dir.
vi.mock('../src/config/paths.js', async () => {
  const actual = await vi.importActual<typeof PathsModule>(
    '../src/config/paths.js',
  );
  return {
    ...actual,
    workbenchCheckoutRoot: () => null,
    bundledFeaturesDir: () => IMAGES_FEATURES_DIR,
  };
});

const { resolveFeatures } = await import('../src/create/scaffold.js');

describe('resolveFeatures — production path (no workbench checkout)', () => {
  it('reads per-feature persistent-home entries from the bundled manifest', () => {
    const resolved = resolveFeatures({
      name: 'prod',
      languages: [],
      services: [],
      features: {
        'ghcr.io/getmonoceros/monoceros-features/claude-code:1': {},
      },
    });

    const claude = resolved.find((f) =>
      f.devcontainerKey.includes('claude-code'),
    );
    expect(claude).toBeDefined();
    // In prod the feature is pulled from GHCR (passthrough ref), NOT the
    // dev-only `./features/<name>` local-source build.
    expect(claude!.devcontainerKey).toBe(
      'ghcr.io/getmonoceros/monoceros-features/claude-code:1',
    );
    // The regression this guards: without the bundle fallback these were
    // empty, so no `../home/.claude` bind was emitted and Claude Code's
    // auth/config was lost on every `apply` rebuild.
    expect(claude!.persistentHomePaths).toContain('.claude');
    expect(claude!.persistentHomeFiles.map((e) => e.path)).toContain(
      '.claude.json',
    );
  });
});
