import { spawn } from 'node:child_process';
import { promises as fs } from 'node:fs';
import { existsSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/**
 * SSH attach point setup for the dev container (ADR 0022).
 *
 * The runtime image runs sshd on loopback; the host reaches it portless
 * through `docker exec … socat … TCP:127.0.0.1:22`. This module is the
 * host-side half: it mints a per-container keypair, drops a small proxy
 * script that resolves the running container by the
 * `devcontainer.local_folder` label (the same handle `monoceros shell`
 * uses, so it follows rebuilds), and registers an OpenSSH `Host
 * monoceros-<name>` block so any SSH-capable IDE (Codium, IntelliJ, Zed)
 * or a plain `ssh monoceros-<name>` attaches with zero config.
 *
 * The container never depends on the builder owning a host SSH key - we
 * always mint our own, scoped to this one container. "No key present" is
 * therefore not an error path.
 */

/** Injectable `ssh-keygen` runner. Tests stub this. */
export type KeygenSpawn = (
  args: readonly string[],
) => Promise<{ exitCode: number; stderr: string }>;

const realKeygen: KeygenSpawn = (args) => {
  return new Promise((resolve, reject) => {
    const child = spawn('ssh-keygen', args as string[], {
      stdio: ['ignore', 'ignore', 'pipe'],
    });
    let stderr = '';
    child.stderr.on('data', (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    child.on('error', reject);
    child.on('exit', (code) => resolve({ exitCode: code ?? 0, stderr }));
  });
};

export interface SetupSshAttachOptions {
  /** Container name (`monoceros-<name>` becomes the SSH host alias). */
  name: string;
  /**
   * Materialized container directory - this is BOTH where the keypair
   * lives (`<targetDir>/.monoceros/ssh/`) and the value of the
   * `devcontainer.local_folder` label the proxy script filters on.
   */
  targetDir: string;
  /** MONOCEROS_HOME - holds `ssh/config.d/<name>` and `ssh/exec-<name>.sh`. */
  home: string;
  /** User SSH dir holding `config`. Defaults to `~/.ssh`; tests override. */
  userSshDir?: string;
  keygen?: KeygenSpawn;
  logger?: { info: (m: string) => void; warn: (m: string) => void };
}

export interface SetupSshAttachResult {
  /** The OpenSSH host alias (`monoceros-<name>`). */
  hostAlias: string;
  /** False when setup was skipped (e.g. `ssh-keygen` unavailable). */
  configured: boolean;
}

/** `~/.ssh`-relative locations Monoceros owns under MONOCEROS_HOME. */
export function sshHomeDir(home: string): string {
  return path.join(home, 'ssh');
}

export function sshConfigEntryPath(home: string, name: string): string {
  return path.join(sshHomeDir(home), 'config.d', name);
}

export function sshProxyScriptPath(home: string, name: string): string {
  return path.join(sshHomeDir(home), `exec-${name}.sh`);
}

function privateKeyPath(targetDir: string): string {
  return path.join(targetDir, '.monoceros', 'ssh', 'id_ed25519');
}

/**
 * Mint a per-container ed25519 keypair if absent (idempotent: an
 * existing keypair is reused so the host alias stays stable across
 * applies). Returns the private/public key paths, or `null` when
 * `ssh-keygen` isn't runnable - the caller degrades gracefully.
 */
async function ensureKeypair(
  targetDir: string,
  name: string,
  keygen: KeygenSpawn,
  logger: { warn: (m: string) => void },
): Promise<{ privateKey: string; publicKey: string } | null> {
  const privateKey = privateKeyPath(targetDir);
  const publicKey = `${privateKey}.pub`;
  if (existsSync(privateKey) && existsSync(publicKey)) {
    return { privateKey, publicKey };
  }
  await fs.mkdir(path.dirname(privateKey), { recursive: true });
  try {
    const res = await keygen([
      '-t',
      'ed25519',
      '-N',
      '',
      '-f',
      privateKey,
      '-C',
      `monoceros-${name}`,
      '-q',
    ]);
    if (res.exitCode !== 0) {
      logger.warn(
        `ssh-keygen failed (exit ${res.exitCode})${res.stderr ? `: ${res.stderr.trim()}` : ''}; IDE SSH attach not set up.`,
      );
      return null;
    }
  } catch (err) {
    logger.warn(
      `ssh-keygen not runnable (${err instanceof Error ? err.message : String(err)}); IDE SSH attach not set up.`,
    );
    return null;
  }
  return { privateKey, publicKey };
}

function proxyScriptContent(name: string, targetDir: string): string {
  return `#!/bin/sh
# Generated by Monoceros (ADR 0022) - do not edit.
# Portless SSH transport into the running dev container '${name}'.
# Resolves the container by the devcontainer.local_folder label (the
# same handle 'monoceros shell' uses), so it follows rebuilds.
set -e
cid=$(docker ps -q \\
  --filter "label=devcontainer.local_folder=${targetDir}" \\
  --filter status=running | head -n1)
if [ -z "$cid" ]; then
  echo "monoceros: dev container '${name}' is not running. Start it with: monoceros apply ${name}" >&2
  exit 1
fi
exec docker exec -i "$cid" socat - TCP:127.0.0.1:22
`;
}

function configEntryContent(
  name: string,
  hostAlias: string,
  privateKey: string,
  proxyScript: string,
): string {
  // Quote the path-valued options so spaces in MONOCEROS_HOME don't
  // break parsing. Host keys are ephemeral (regenerated per container in
  // the entrypoint), so host-key checking is disabled - there is no
  // persistent identity to pin and it would only nag across rebuilds.
  return `# Generated by Monoceros (ADR 0022) - do not edit.
# Attach an SSH-capable IDE (Codium, IntelliJ, Zed) to host
# '${hostAlias}', or run: ssh ${hostAlias}
Host ${hostAlias}
    User node
    IdentityFile "${privateKey}"
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ProxyCommand "${proxyScript}"
`;
}

/**
 * Idempotently prepend `Include <home>/ssh/config.d/*` to the user's
 * `~/.ssh/config` so every container's generated entry is picked up.
 * Additive and clearly marked - existing entries are never rewritten.
 */
async function ensureInclude(userSshDir: string, home: string): Promise<void> {
  const configPath = path.join(userSshDir, 'config');
  const includeTarget = path.join(sshHomeDir(home), 'config.d', '*');
  const includeLine = `Include "${includeTarget}"`;

  await fs.mkdir(userSshDir, { recursive: true });
  let existing = '';
  try {
    existing = await fs.readFile(configPath, 'utf8');
  } catch {
    existing = '';
  }
  // Match the exact include target regardless of surrounding quotes.
  if (existing.includes(includeTarget)) return;

  const banner =
    '# Added by Monoceros (ADR 0022): per-container SSH attach entries.';
  const prefix = `${banner}\n${includeLine}\n`;
  const next = existing.length > 0 ? `${prefix}\n${existing}` : prefix;
  await fs.writeFile(configPath, next, { mode: 0o600 });
  await fs.chmod(configPath, 0o600).catch(() => {});
}

export async function setupSshAttach(
  opts: SetupSshAttachOptions,
): Promise<SetupSshAttachResult> {
  const hostAlias = `monoceros-${opts.name}`;
  const logger = opts.logger ?? { info: () => {}, warn: () => {} };
  const keygen = opts.keygen ?? realKeygen;
  const userSshDir = opts.userSshDir ?? path.join(os.homedir(), '.ssh');

  const keys = await ensureKeypair(opts.targetDir, opts.name, keygen, logger);
  if (!keys) return { hostAlias, configured: false };

  const proxyScript = sshProxyScriptPath(opts.home, opts.name);
  const configEntry = sshConfigEntryPath(opts.home, opts.name);

  await fs.mkdir(path.dirname(proxyScript), { recursive: true });
  await fs.mkdir(path.dirname(configEntry), { recursive: true });

  await fs.writeFile(
    proxyScript,
    proxyScriptContent(opts.name, opts.targetDir),
    { mode: 0o755 },
  );
  await fs.chmod(proxyScript, 0o755).catch(() => {});
  await fs.writeFile(
    configEntry,
    configEntryContent(opts.name, hostAlias, keys.privateKey, proxyScript),
  );

  await ensureInclude(userSshDir, opts.home);

  return { hostAlias, configured: true };
}

/**
 * Tear down the host-side SSH attach artifacts for a container
 * (`monoceros remove`). The keypair lives under the container dir, which
 * `remove` deletes wholesale; this clears the MONOCEROS_HOME-side proxy
 * script and config.d entry. The `Include` line in `~/.ssh/config` is
 * left in place - it harmlessly globs an empty/!existent dir and other
 * containers still rely on it.
 */
export async function removeSshAttach(
  home: string,
  name: string,
): Promise<void> {
  await fs.rm(sshProxyScriptPath(home, name), { force: true });
  await fs.rm(sshConfigEntryPath(home, name), { force: true });
}
